services:
  nginx:
    image: nginx:1.23
    restart: always
    depends_on:
      - django
    ports:
      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}
      - ${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/certs:/etc/ssl/certs:ro
      - ./django/static:/app/static:ro
      - ./django/media/public:/app/media/public:ro
    env_file:
      - .env

  django:
    build: ./django
    restart: always
    command: daphne config.asgi:application -b 0.0.0.0 -p ${DJANGO_PORT}
    depends_on:
      - postgresql
      - redis
      - rabbitmq
    expose:
      - ${DJANGO_PORT}
    volumes:
      - ./django:/app
      - .env:/app/.env
    env_file:
      - .env

  celery:
    build: ./django
    restart: always
    command: celery -A config worker --loglevel=info
    depends_on:
      - django
      - rabbitmq
    volumes:
      - ./django:/app
    env_file:
      - .env

  postgresql:
    image: postgres:16
    restart: always
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always
    expose:
      - ${REDIS_PORT}
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    expose:
      - ${RABBITMQ_PORT}
    ports:
      - "15672:15672"
    env_file:
      - .env

volumes:
  postgres_data: