services:
  django:
    build: ./django
    restart: always
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    depends_on:
      - postgresql
      - redis
      - rabbitmq
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - ./django:/app
      - .env:/app/.env
    env_file:
      - .env

  celery:
    build: ./django
    restart: always
    command: celery -A config worker --loglevel=info
    depends_on:
      - django
      - rabbitmq
    volumes:
      - ./django:/app
    env_file:
      - .env

  postgresql:
    image: postgres:16
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always
    expose:
      - ${REDIS_PORT}
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    expose:
      - ${RABBITMQ_PORT}
    ports:
      - "15672:15672"
    env_file:
      - .env

volumes:
  postgres_data: